Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

AllCops:
    SuggestExtensions: false

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*.rb'
